<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\CrossCutting\Filoroch.Template.CrossCutting\Filoroch.Template.CrossCutting.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\IoC\Filoroch.Template.IoC\Filoroch.Template.IoC.csproj" />
    <ProjectReference Include="..\..\Application\Filoroch.Template.Application\Filoroch.Template.Application.csproj" />
  </ItemGroup>
</Project>
